### PR TITLE
Allowing the local users to the main team

### PR DESCRIPTION
**Pull request by ringods**
When using local auth, the v4 config requires the setting I added to the template, otherwise concourse web complains that no auth has been defined.

### CODE REVIEW

**Comment by ringods** [comment]
Hello @iuriaranda, you have a point that allow all the users is not a good idea. But if you look carefully, the option being set is only used when specifying a local user, not when specifying Github auth. So all users of this module using Github are not impacted.

Nevertheless, would you be more comfortable accepting the change if I update it by using `CONCOURSE_MAIN_TEAM_LOCAL_USER`? This would restrict access to the main team to 1 local user then.

Context: I'm helping a customer set up Concourse. They need Bitbucket Auth which is not supported by this module. So for the time being, we set it up with local auth and the support for Bitbucket auth will be a next PR. 😉

**Comment by iuriaranda** [comment]
Hi @ringods , it's true that the flag is only being set when you configure a local user. But if it's set, it'll also affect all other authentication methods. For example, if you set a local user and also enable Github, all Github users that can login to concourse will also have access to the main team.

For our use-case, we normally enable Github authentication and we also create a single local user, which should only have access to the customer team. The local user is used for the [`concourse-pipeline` resource](https://github.com/concourse/concourse-pipeline-resource), as it doesn't support Github auth. So in our case we don't want that local user to have access to the main team either.

Having said that, I propose you to create a new optional variable named something like `main_team_local_users` in the module, where you can set a list of all the local users you want to have access to the main team. Then set the corresponding Concourse environment variable (`CONCOURSE_MAIN_TEAM_LOCAL_USER`) only if the module variable is not empty.

I would also accept the `CONCOURSE_MAIN_TEAM_ALLOW_ALL_USERS` flag if:
- it's being set independently of any auth method
- it can be toggled on and off via a variable
- it's off by default

Do you think any of these suggestions will fit your needs?

By the way, Bitbucket auth support would be really welcomed 😛

**Comment by ringods** [comment]
@iuriaranda I have updated the PR with a separate option to specify the local user which can have access to the main team. With the current state of the module, you can only create a single local user at the moment. As a result, I made the new option `concourse_auth_main_team_local_user` a single string value rather than a list.

**Comment by iuriaranda** [comment]
@ringods I've created a new release ([`9.8.0`](https://github.com/skyscrapers/terraform-concourse/releases/tag/9.8.0)) that includes your changes 🙂

**Pull request merged**
